########## Wait Timing ###############
Low=5000
Medium=10000
High=20000

############# Account Details ############
Naukari_User1=kishoretarunuem@gmail.com
Naukari_Password1=Qwe123Asd


############ URL ################
URL_Youtube=https://www.youtube.com
URL_naukari=https://www.naukri.com/mnjuser/homepage