########## Wait Timing ###############
Low=5
Medium=10
High=20

############# Account Details ############
Naukari_User1=kishoretarunuem@gmail.com
Password=UXdlMTIzQXNk
Instahyre_UserName=kishoretarunuem@gmail.com


############ URL ################
URL_Youtube=https://www.youtube.com
URL_naukari=https://www.naukri.com/mnjuser/homepage
URL_Instahyre1=https://www.instahyre.com/login/
URL_Instahyre=https://www.instahyre.com/candidate/opportunities/?matching=true