########## Wait Timing ###############
Low=5
Medium=10
High=20

############# Account Details ############
UserName=kishoretarunuem@gmail.com
Password=UTFXMkBzeCNAMXc=


############ URL ################
URL_Youtube=https://www.youtube.com
URL_naukari=https://www.naukri.com/mnjuser/homepage
URL_Instahyre1=https://www.instahyre.com/login/
URL_Instahyre=https://www.instahyre.com/candidate/opportunities/?matching=true
URL_TestAutomationPractice=https://testautomationpractice.blogspot.com/
URL_DummyTickets=https://dummy-tickets.com/buyticket
URL_DummyTicket=https://www.dummyticket.com/dummy-ticket-for-visa-application/
URL_contextMenu=https://swisnl.github.io/jQuery-contextMenu/demo.html
URL_dragAndDrop=http://www.dhtmlgoodies.com/scripts/drag-drop-custom/demo-drag-drop-3.html

