############ Youtube ######################

Youtube_Search_Icon=(//button[@title='Search'])[1]
Youtube_Search_Box=(//input[@name='search_query'])[1]
Video_TMKOC_123=(//a[@id='video-title'])[5]
Video_TMKOC_101=(//a[@id='video-title'])[12]
Video_TMKOC_107=(//a[@id='video-title'])[4]
Video_TMKOC_103=(//a[@id='video-title'])[13]
Video_TMKOC_100=(//a[@id='video-title'])[6]


############ Naukari ######################

Naukari_logo=//img[@alt='Naukri Logo']
Naukari_loginForm=//form[@id='loginForm']
Naukari_Employment=(//span[text()='Employment'])[2]
Naukari_Projects=(//span[text()='Projects'])[2]
Naukari_Personal_details=(//span[text()='Personal details'])[2]
Naukari_Update_resume=//input[@type='button' and @value='Update resume']
Personal_details=(//span[text()='Personal details'])[2]
Date_of_Birth=//div[text()='Date of birth']
Naukari_UpdateResume_Resume=//div[text()='Resume']
Personal_details_header=(//div[@class='widgetHead'])[8]
Naukari_ViewProfile_AboutUs=//a[@title='About us']
Naukari_ViewProfile=(//a[@href='/mnjuser/profile'])[1]
Naukari_Profile=//a[text()='View' and text()=' profile']
Naukari_Login=//button[text()='Login']
Resume_Headline_text=//div[contains(text(),'To be the part of an enthusiastic work environment')]
Naukari_Job_Tab=//div[text()='Jobs']
Naukari_Job_Recommended=//div[text()='Recommended jobs']
Naukari_Job_Recommended_CheckBox=//i[@class='dspIB naukicon naukicon-ot-checkbox']
Naukari_Job_Apply=//button[contains(text(),'Apply')]
Naukari_Job_Apply_Que_textBox=//div[@class='textAreaWrapper']
Naukari_UserName=//input[@type='text' and @placeholder='Enter Email ID / Username']
Naukari_Password=//input[@type='password' and @placeholder='Enter Password']



############ Instahyre ######################
instahyre_Resume=//*[@id="resume"]/h6
Job_Preferences=//*[@id="job-preferences"]/a
Diversity_info=//*[@id="diversity-info"]/h6
Instahyre_Login_button=//button[text()='Login']
Profile_Tab_header=//a[text()='Profile']
Instahyre_UserName=//input[@type='text' and @name='email']
Instahyre_Password=//input[@type='password' and @name='password']
Instahyre_Searchjobs=//h6[text()='Search other jobs']
Instahyre_TarunSQA=//li[@id='search-TarunSQA']
Instahyre_View=(//button[@id='interested-btn' and contains(text(),'View')])[1]
Instahyre_Apply=(//button[contains(text(),'Apply')])[1]
Instahyre_JobList=(//a[@id='employer-profile-opportunity'])[1]
Instahyre_Searchjobs_Down=//i[@class='fa ng-scope fa-angle-down']
Instahyre_Searchjobs_Up=//i[@class='fa ng-scope fa-angle-up']


##################### Foundit Monster ######################
Foundit_LoginViaPass=//div[@class='loginWith']
Foundit_UserName=//input[@id='signInName']
Foundit_Password=//input[@id='password']
Foundit_Login=//input[@id='signInbtn']
Founfit_Profile=//span[@class='w-20 truncate text-xs']
Founfit_ViewProfile=//a[@href='/seeker/profile']
Foundit_Resume_Delete_Button=(//button[@type='button'])[6]
Foundit_Upload_Resume=(//button[@type='button'])[5]

########################
Week_Day_CheckBox1=//input[@id='sunday']
Week_Day_CheckBox=//input[@class='form-check-input' and @type='checkbox']

































































